/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.Buss;
import DTO.CT_ctkm;
import java.util.Set;
import DTO.ChitietHoaDon;
import DTO.ReportView;
import DTO.product;
import DTO.top_sanpham;
import com.itextpdf.text.DocumentException;
import java.sql.ResultSet;
import com.mysql.jdbc.ResultSetRow;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen
 */
public class BanHang extends javax.swing.JFrame {

    /**
     * Creates new form BanHang
     */
    private String maKH;
    private String maNV;
    private String ngay;
    private String maHD;
    Buss buss = null;
    DefaultTableModel tablemodel;
    DefaultTableModel tablemodel1;
    DefaultTableModel tablemodel2;

    ArrayList<ChitietHoaDon> dsct = new ArrayList<>();

    public BanHang(String makh, String manv, String ngay1) {
        initComponents();
        maKH = makh;
        maNV = manv;
        ngay = ngay1;
        jTextField_MaKhachHang.setText(maKH);
        jTextField_MaNV.setText(maNV);
        jTextField_ngaylap.setText(ngay);
        try {
            tablemodel = (DefaultTableModel) jTable_SanPham.getModel();
            tablemodel1 = (DefaultTableModel) jTable_GioHang.getModel();
            tablemodel2 = (DefaultTableModel) jTable_Voucher.getModel();
            buss = new Buss();
            maHD = buss.getMaHd(manv, makh);
            jTextField_MaHoaDon.setText(maHD);
            loadDataSP();
        } catch (SQLException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private BanHang() {
    }

    private void loadDataSP() throws SQLException {
        ArrayList<product> ds = new ArrayList<>();
        ds = buss.getProducts();
        tablemodel.setRowCount(0);
        int i = 1;
        System.out.println(i);
        for (product sp : ds) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(sp.getSpID());
            vctData.add(sp.getSpName());

            vctData.add(Integer.parseInt(sp.getGia()) + (Integer.parseInt(sp.getGia()) * Integer.parseInt(sp.getLaixuat())) / 100);
            vctData.add(sp.getNccID());
////
//         
            vctData.add(sp.getSoluong());
            vctData.add(sp.getMota());

            tablemodel.addRow(vctData);

        }
    }

    private void loadData(ArrayList<ChitietHoaDon> ds) throws SQLException {
        tablemodel1.setRowCount(0);
        int i = 1;
        for (ChitietHoaDon sp : ds) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(sp.getMahd());
            vctData.add(sp.getMaSP());

            vctData.add(sp.getSoluong());
            vctData.add(sp.getDongia());
            vctData.add(sp.getTongtien());

            tablemodel1.addRow(vctData);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_SanPham = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_GioHang = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_MaHoaDon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_MaSP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_DonGiaSP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_SoLuongSP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_MaKhachHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton_ThemGH = new javax.swing.JButton();
        jButton_XoaGH = new javax.swing.JButton();
        jTextField_TenSP = new javax.swing.JTextField();
        jLabel17IMG = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField_ThanhTienSP = new javax.swing.JTextField();
        jTextField_MaNV = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_ngaylap = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton_ThanhToan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabelTongCong = new javax.swing.JLabel();
        jLabelVanchuyen = new javax.swing.JLabel();
        jLabelvoucher = new javax.swing.JLabel();
        jLabelThanhTien = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Voucher = new javax.swing.JTable();
        jTextField_voucher = new javax.swing.JTextField();
        jButton_ThemHD1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTable_SanPham.setBackground(new java.awt.Color(255, 248, 233));
        jTable_SanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_SanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Nhà cung cấp", "Số lượng", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_SanPham.setGridColor(new java.awt.Color(255, 253, 250));
        jTable_SanPham.setSelectionBackground(new java.awt.Color(239, 214, 173));
        jTable_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_SanPham);

        jPanel8.setBackground(new java.awt.Color(217, 173, 109));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh Sách Sản Phẩm");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jTable_GioHang.setBackground(new java.awt.Color(255, 248, 233));
        jTable_GioHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_GioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_GioHang.setGridColor(new java.awt.Color(255, 253, 250));
        jTable_GioHang.setSelectionBackground(new java.awt.Color(239, 214, 173));
        jTable_GioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_GioHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_GioHang);

        jPanel9.setBackground(new java.awt.Color(217, 173, 109));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Giỏ Hàng");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 247, 229));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 225, 225), 1, true), "Thông Tin Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(159, 132, 61))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã hóa đơn");

        jTextField_MaHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_MaHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 195, 130)));
        jTextField_MaHoaDon.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mã sản phẩm");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tên sản phẩm");

        jTextField_MaSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_MaSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 195, 130)));
        jTextField_MaSP.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Đơn Giá");

        jTextField_DonGiaSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_DonGiaSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 195, 130)));
        jTextField_DonGiaSP.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Số lượng");

        jTextField_SoLuongSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_SoLuongSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 195, 130)));
        jTextField_SoLuongSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_SoLuongSPFocusLost(evt);
            }
        });
        jTextField_SoLuongSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_SoLuongSPKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Mã khách hàng");

        jTextField_MaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_MaKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 195, 130)));
        jTextField_MaKhachHang.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã nhân viên");

        jButton_ThemGH.setBackground(new java.awt.Color(153, 255, 153));
        jButton_ThemGH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_ThemGH.setText("Thêm vào  giỏ");
        jButton_ThemGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemGHActionPerformed(evt);
            }
        });

        jButton_XoaGH.setBackground(new java.awt.Color(204, 51, 0));
        jButton_XoaGH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_XoaGH.setForeground(new java.awt.Color(255, 255, 255));
        jButton_XoaGH.setText("Xóa");
        jButton_XoaGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaGHActionPerformed(evt);
            }
        });

        jTextField_TenSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_TenSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 195, 130)));
        jTextField_TenSP.setEnabled(false);

        jLabel17IMG.setBackground(new java.awt.Color(204, 255, 255));
        jLabel17IMG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17IMG.setOpaque(true);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Thành tiền");

        jTextField_ThanhTienSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_ThanhTienSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 195, 130)));
        jTextField_ThanhTienSP.setEnabled(false);

        jTextField_MaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_MaNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 195, 130)));
        jTextField_MaNV.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Ngày lập");

        jTextField_ngaylap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_ngaylap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 195, 130)));
        jTextField_ngaylap.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_MaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_ngaylap, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_SoLuongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_DonGiaSP))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_TenSP))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addComponent(jLabel17IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_ThemGH, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jButton_XoaGH, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jTextField_ThanhTienSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_MaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_ngaylap, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_DonGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_SoLuongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ThanhTienSP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel17IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_XoaGH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ThemGH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 247, 229));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 225, 225), 1, true), "Danh sách chi tiết hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(159, 132, 61))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton_ThanhToan.setBackground(new java.awt.Color(153, 255, 153));
        jButton_ThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_ThanhToan.setText("Thanh Toán Và In Hóa Đơn");
        jButton_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThanhToanActionPerformed(evt);
            }
        });

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFocusTraversalPolicyProvider(true);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Tổng cộng");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Phí vận chuyển");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Voucer giảm giá");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Thành tiền");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(37, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabelTongCong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTongCong.setText("0");

        jLabelVanchuyen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelVanchuyen.setText("15.000đ");

        jLabelvoucher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelThanhTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelThanhTien.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTongCong, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVanchuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelvoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 58, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTongCong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelVanchuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelvoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Voucer giảm giá");

        jTable_Voucher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_Voucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên voucher", "Mã voucher", "Số tiền giảm", "Ngày hết hạn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Voucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_VoucherMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_Voucher);

        jTextField_voucher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_voucher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 195, 130)));

        jButton_ThemHD1.setBackground(new java.awt.Color(153, 255, 153));
        jButton_ThemHD1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_ThemHD1.setText("Tìm");
        jButton_ThemHD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemHD1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_voucher, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton_ThemHD1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 202, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_voucher, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ThemHD1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButton_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThemHD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemHD1ActionPerformed
        tablemodel2.setRowCount(0);
        try {
            HashMap<String, Object> list = buss.findCTKM(jTextField_voucher.getText());
            Set<String> keySet = list.keySet();
            Vector dataa = new Vector();

            for (String key : keySet) {
//            System.out.println(key + " - " + list.get(key));
                dataa.add(list.get(key));
            }
            tablemodel2.addRow(dataa);

        } catch (SQLException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton_ThemHD1ActionPerformed

    private void jButton_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThanhToanActionPerformed

        for (ChitietHoaDon chitietHoaDon : dsct) {
            try {
                int x = 0;
                if (!jLabelvoucher.getText().trim().equalsIgnoreCase("")) {
                    x = Integer.parseInt(jLabelvoucher.getText());
                }
                chitietHoaDon.setTiengiamgia(String.valueOf(x));
                int s = Integer.parseInt(chitietHoaDon.getTongtien()) - x;
                if (s < 0) {
                    s = 0;
                }
                chitietHoaDon.setThanhtien(String.valueOf(s));
                buss.insertHoaDonCT(chitietHoaDon);
                int z = Integer.parseInt(buss.getSLSP(chitietHoaDon.getMaSP()));
                buss.updateSL_MuaHang(chitietHoaDon.getMaSP(),String.valueOf(z-Integer.parseInt(chitietHoaDon.getSoluong())));
                top_sanpham top = new top_sanpham(chitietHoaDon.getMaSP(), chitietHoaDon.getSoluong(), jTextField_ngaylap.getText(), chitietHoaDon.getTongtien());
                buss.inserspTOP(top);

            } catch (SQLException ex) {
                Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        try {
            JOptionPane.showMessageDialog(rootPane, "Cảm ơn bạn đã tin tưởng và mua hàng , xin hẹn gặp lại quý khách");
            buss.update_Tien_HoaDon(jTextField_MaHoaDon.getText(), jLabelThanhTien.getText());
            buss.xuatPDF_CT_HD(dsct, "C:\\Users\\Nguyen\\Desktop\\donhang.pdf", "");
            
        } catch (DocumentException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_ThanhToanActionPerformed
    public int checkMaSP(String masp) {

        for (int i = 0; i < dsct.size(); i++) {
            if (dsct.get(i).getMaSP().equalsIgnoreCase(masp)) {
                return i;
            }
        }
        return -1;

    }

    public int sumSP() {
        int s = 0;
        for (ChitietHoaDon chitietHoaDon : dsct) {
            s += Integer.parseInt(chitietHoaDon.getTongtien());
        }
        return s;
    }
    private void jButton_ThemGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemGHActionPerformed

        if (jTextField_SoLuongSP.getText() == "" || !isNumeric(jTextField_SoLuongSP.getText())) {
            JOptionPane.showMessageDialog(null, "Số lượng bắt buộc phải là số nguyên");
        } else {
            if (jTextField_DonGiaSP.getText() == "") {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm cần thêm");

            } else {
                int s = Integer.parseInt(jTextField_SoLuongSP.getText()) * Integer.parseInt(jTextField_DonGiaSP.getText());
                jTextField_ThanhTienSP.setText(String.valueOf(s));
                int c = checkMaSP(jTextField_MaSP.getText());
                
                if (c != -1) {
                    dsct.get(c).setSoluong(jTextField_SoLuongSP.getText());
                    dsct.get(c).setTongtien(String.valueOf(Integer.parseInt(dsct.get(c).getSoluong()) * Integer.parseInt(dsct.get(c).getDongia())));
                } else {
//                    System.out.println("");
                    ChitietHoaDon ct = new ChitietHoaDon(jTextField_MaHoaDon.getText(), jTextField_MaSP.getText(), jTextField_SoLuongSP.getText(), jTextField_DonGiaSP.getText(), String.valueOf(Integer.parseInt(jTextField_SoLuongSP.getText()) * Integer.parseInt(jTextField_DonGiaSP.getText())),"0","0");
                    dsct.add(ct);
                }
                try {
                    loadData(dsct);
//                    System.out.println(sumSP());
                    jLabelTongCong.setText(String.valueOf(sumSP()));
                    if (jLabelvoucher.getText() != "") {
                    if (Integer.parseInt(jLabelTongCong.getText()) + 15000 - Integer.parseInt(jLabelvoucher.getText()) <= 0) {
                        jLabelThanhTien.setText("0");
                    } else {
                        jLabelThanhTien.setText(String.valueOf(Integer.parseInt(jLabelTongCong.getText()) + 15000 - Integer.parseInt(jLabelvoucher.getText())));
                    }
                } else {
                    jLabelThanhTien.setText(String.valueOf(Integer.parseInt(jLabelTongCong.getText()) + 15000));
                }
                } catch (SQLException ex) {
                    Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


    }//GEN-LAST:event_jButton_ThemGHActionPerformed
    public ImageIcon ResizeImage(String imagePath, byte[] pic) {
        ImageIcon myImage = null;
        if (imagePath != null) {
            myImage = new ImageIcon(imagePath);
        } else {
            myImage = new ImageIcon(pic);
        }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(jLabel17IMG.getWidth(), jLabel17IMG.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
    private void jTable_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SanPhamMouseClicked
        int i = jTable_SanPham.getSelectedRow();

        if (Integer.parseInt(String.valueOf(tablemodel.getValueAt(i, 5))) <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Sản phẩm hiện tại đang hết hàng :( Xin lỗi vì sự bất tiện này");
        } else {
            jTextField_MaSP.setText(buss.getDsProduct().get(i).getSpID());
            jTextField_TenSP.setText(buss.getDsProduct().get(i).getSpName());
            jTextField_DonGiaSP.setText(String.valueOf(tablemodel.getValueAt(i, 3)));
            jTextField_SoLuongSP.setText("1");
            ImageIcon img = null;

            img = ResizeImage(null, buss.getDsProduct().get(i).getImg());

            jLabel17IMG.setIcon(img);
        }
    }//GEN-LAST:event_jTable_SanPhamMouseClicked
    public static boolean isNumeric(String str) {
        return str.matches("-?\\d+(\\.\\d+)?");
    }
    private void jTextField_SoLuongSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SoLuongSPFocusLost

        if (jTextField_SoLuongSP.getText() == "" || !isNumeric(jTextField_SoLuongSP.getText())) {
            JOptionPane.showMessageDialog(null, "Số lượng bắt buộc phải là số nguyên");
        } else {
            if (jTextField_DonGiaSP.getText() == "") {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm cần thêm");

            } else {
                int s = Integer.parseInt(jTextField_SoLuongSP.getText()) * Integer.parseInt(jTextField_DonGiaSP.getText());
                jTextField_ThanhTienSP.setText(String.valueOf(s));
                int c = checkMaSP(jTextField_MaSP.getText());
            }
        }

    }//GEN-LAST:event_jTextField_SoLuongSPFocusLost

    private void jButton_XoaGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaGHActionPerformed
        int x = checkMaSP(jTextField_MaSP.getText());
        if (x != -1) {
            dsct.remove(x);
        }
        try {
            loadData(dsct);
            jLabelTongCong.setText(String.valueOf(sumSP()));
            jLabelThanhTien.setText(String.valueOf(Integer.parseInt(jLabelTongCong.getText()) + 15000));
        } catch (SQLException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_XoaGHActionPerformed

    private void jTable_GioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_GioHangMouseClicked

        int i = jTable_GioHang.getSelectedRow();

        jTextField_MaSP.setText(dsct.get(i).getMaSP());
        jTextField_TenSP.setText((String) tablemodel1.getValueAt(i, 2));
        jTextField_SoLuongSP.setText((String) tablemodel1.getValueAt(i, 3));
        jTextField_DonGiaSP.setText((String) tablemodel1.getValueAt(i, 4));
        jTextField_ThanhTienSP.setText((String) tablemodel1.getValueAt(i, 5));
        


    }//GEN-LAST:event_jTable_GioHangMouseClicked

    private void jTextField_SoLuongSPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SoLuongSPKeyPressed

        if (jTextField_SoLuongSP.getText() == "" && !isNumeric(jTextField_SoLuongSP.getText())) {
            JOptionPane.showMessageDialog(null, "Số lượng bắt buộc phải là số nguyên");
        } else {
            if (jTextField_DonGiaSP.getText() == "") {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm cần thêm");

            } else {
                int s = Integer.parseInt(jTextField_SoLuongSP.getText()) * Integer.parseInt(jTextField_DonGiaSP.getText());
                jTextField_ThanhTienSP.setText(String.valueOf(s));
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SoLuongSPKeyPressed

    private void jTable_VoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_VoucherMouseClicked

        int i = jTable_Voucher.getSelectedRow();
        int x = Integer.parseInt(String.valueOf(tablemodel2.getValueAt(i, 2)));
        jLabelvoucher.setText(String.valueOf(tablemodel2.getValueAt(i, 2)));

        String s = "";
        if (Integer.parseInt(jLabelTongCong.getText()) + 15000 - x <= 0) {
            s = "0";
        } else {
            s = String.valueOf(Integer.parseInt(jLabelTongCong.getText()) + 15000 - x);
        }
        jLabelThanhTien.setText(s);

    }//GEN-LAST:event_jTable_VoucherMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ThanhToan;
    private javax.swing.JButton jButton_ThemGH;
    private javax.swing.JButton jButton_ThemHD1;
    private javax.swing.JButton jButton_XoaGH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17IMG;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelThanhTien;
    private javax.swing.JLabel jLabelTongCong;
    private javax.swing.JLabel jLabelVanchuyen;
    private javax.swing.JLabel jLabelvoucher;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_GioHang;
    private javax.swing.JTable jTable_SanPham;
    private javax.swing.JTable jTable_Voucher;
    private javax.swing.JTextField jTextField_DonGiaSP;
    private javax.swing.JTextField jTextField_MaHoaDon;
    private javax.swing.JTextField jTextField_MaKhachHang;
    private javax.swing.JTextField jTextField_MaNV;
    private javax.swing.JTextField jTextField_MaSP;
    private javax.swing.JTextField jTextField_SoLuongSP;
    private javax.swing.JTextField jTextField_TenSP;
    private javax.swing.JTextField jTextField_ThanhTienSP;
    private javax.swing.JTextField jTextField_ngaylap;
    private javax.swing.JTextField jTextField_voucher;
    // End of variables declaration//GEN-END:variables
}
