/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.Buss;
import DTO.CT_ctkm;
import DTO.CtKm;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KHANH
 */
public class CTKM extends javax.swing.JFrame {

    /**
     * Creates new form CTKM
     */
    Buss buss = null;
    DefaultTableModel tablemodel = null;
    DefaultTableModel tablemodel1 = null;

    public CTKM() {
        initComponents();
        try {
            buss = new Buss();

            tablemodel = (DefaultTableModel) jTable_DanhSachCTGG.getModel();
            tablemodel1 = (DefaultTableModel) jTable_ChiTietCTGG.getModel();
            loadData();
            
        } catch (SQLException ex) {
            Logger.getLogger(CTKM.class.getName()).log(Level.SEVERE, null, ex);
        }
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DanhSachCTGG = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ChiTietCTGG = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_MaGiamGia = new javax.swing.JTextField();
        jTextField_TenCTGG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Loai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_DieuKien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_NoiDung = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton_ThemCTGG = new javax.swing.JButton();
        jButton_SuaCTGG = new javax.swing.JButton();
        jButton_XoaCTGG = new javax.swing.JButton();
        jButton_ResetCTGG = new javax.swing.JButton();
        jTextField_NgayNhap = new com.toedter.calendar.JDateChooser();
        jTextField_NgayNhap1 = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_MaGiamGiaCT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_MagiamgiaCT1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_masp = new javax.swing.JTextField();
        jButton_ThemCT = new javax.swing.JButton();
        jButton_XoaCT = new javax.swing.JButton();
        jButton_ResetCT = new javax.swing.JButton();
        jButton_SuaCT = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField_HInhThucCT1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chương Trình KM");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách chương trình giảm giá");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        jTable_DanhSachCTGG.setBackground(new java.awt.Color(153, 255, 255));
        jTable_DanhSachCTGG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_DanhSachCTGG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Mã giảm giá", "Tên chương trình", "Mã Code", "Thời gian bắt đầu", "Thời gian kết thúc", "Nội dung", "Điều kiện"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DanhSachCTGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DanhSachCTGGMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DanhSachCTGG);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(0, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Chi tiết chương trình giảm giá");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jTable_ChiTietCTGG.setBackground(new java.awt.Color(153, 255, 255));
        jTable_ChiTietCTGG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_ChiTietCTGG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Mã CT giảm giá", "Mã code", "Mã giảm giá", "Hình thức"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_ChiTietCTGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ChiTietCTGGMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_ChiTietCTGG);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(153, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Chương trình giảm giá", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã giảm giá");

        jTextField_MaGiamGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_MaGiamGia.setEnabled(false);

        jTextField_TenCTGG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên ");

        jTextField_Loai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mã Code");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Thời gian bắt đầu");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Thời gian kết thúc");

        jTextField_DieuKien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_DieuKien.setText("Những ai có được mã");
        jTextField_DieuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DieuKienActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Điều kiện");

        jTextField_NoiDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nội dung");

        jButton_ThemCTGG.setBackground(new java.awt.Color(102, 255, 102));
        jButton_ThemCTGG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_ThemCTGG.setText("Thêm");
        jButton_ThemCTGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemCTGGActionPerformed(evt);
            }
        });

        jButton_SuaCTGG.setBackground(new java.awt.Color(51, 153, 255));
        jButton_SuaCTGG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_SuaCTGG.setText("Sửa");
        jButton_SuaCTGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaCTGGActionPerformed(evt);
            }
        });

        jButton_XoaCTGG.setBackground(new java.awt.Color(255, 51, 51));
        jButton_XoaCTGG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_XoaCTGG.setText("Xóa");
        jButton_XoaCTGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaCTGGActionPerformed(evt);
            }
        });

        jButton_ResetCTGG.setBackground(new java.awt.Color(204, 204, 204));
        jButton_ResetCTGG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_ResetCTGG.setText("Reset");
        jButton_ResetCTGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetCTGGActionPerformed(evt);
            }
        });

        jTextField_NgayNhap.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_NgayNhap.setDateFormatString("dd/MM/yyyy");
        jTextField_NgayNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_NgayNhap1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_NgayNhap1.setDateFormatString("dd/MM/yyyy");
        jTextField_NgayNhap1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_MaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TenCTGG, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_DieuKien, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jTextField_NgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_NgayNhap1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jTextField_NoiDung))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton_ThemCTGG, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_SuaCTGG, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButton_XoaCTGG, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton_ResetCTGG, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_MaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_NgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TenCTGG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_NgayNhap1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_DieuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_NoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ThemCTGG, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_SuaCTGG, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_XoaCTGG, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ResetCTGG, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(153, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Chi tiết chương trình giảm giá", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Mã CT giảm giá");

        jTextField_MaGiamGiaCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_MaGiamGiaCT.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Mã giảm giá");

        jTextField_MagiamgiaCT1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_MagiamgiaCT1.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Mã Code");

        jTextField_masp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_masp.setEnabled(false);
        jTextField_masp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_maspActionPerformed(evt);
            }
        });

        jButton_ThemCT.setBackground(new java.awt.Color(102, 255, 102));
        jButton_ThemCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_ThemCT.setText("Thêm");
        jButton_ThemCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemCTActionPerformed(evt);
            }
        });

        jButton_XoaCT.setBackground(new java.awt.Color(255, 51, 51));
        jButton_XoaCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_XoaCT.setText("Xóa");
        jButton_XoaCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaCTActionPerformed(evt);
            }
        });

        jButton_ResetCT.setBackground(new java.awt.Color(204, 204, 204));
        jButton_ResetCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_ResetCT.setText("Reset");
        jButton_ResetCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetCTActionPerformed(evt);
            }
        });

        jButton_SuaCT.setBackground(new java.awt.Color(51, 153, 255));
        jButton_SuaCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_SuaCT.setText("Sửa");
        jButton_SuaCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaCTActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Số  tiền giảm");

        jTextField_HInhThucCT1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton_ThemCT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jTextField_HInhThucCT1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jTextField_MagiamgiaCT1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jTextField_MaGiamGiaCT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_masp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jButton_SuaCT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jButton_XoaCT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                        .addComponent(jButton_ResetCT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(14, 14, 14))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_MaGiamGiaCT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_MagiamgiaCT1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_masp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_HInhThucCT1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ThemCT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_XoaCT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ResetCT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_SuaCT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_DieuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DieuKienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DieuKienActionPerformed

    private void jButton_ThemCTGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemCTGGActionPerformed

        int i = jTable_DanhSachCTGG.getSelectedRow();

        if (jTextField_TenCTGG.getText().trim().equals("") || jTextField_NoiDung.getText().trim().equals("") || jTextField_DieuKien.getText().trim().equals("") || jTextField_NgayNhap.getDate().equals("") || jTextField_NgayNhap1.getDate().equals("") || jTextField_Loai.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được bỏ trống");

        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String addDateBD = dateFormat.format(jTextField_NgayNhap.getDate());
            String addDateKT = dateFormat.format(jTextField_NgayNhap1.getDate());
            CtKm km = new CtKm(jTextField_MaGiamGia.getText(), jTextField_TenCTGG.getText(), jTextField_Loai.getText(), addDateBD, addDateKT, jTextField_NoiDung.getText(), jTextField_DieuKien.getText());
            try {
                boolean x = buss.insertCTKM(km);
                if (x) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                    loadData(buss.getCtKms());
                }
            } catch (SQLException ex) {
                Logger.getLogger(CTKM.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CTKM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton_ThemCTGGActionPerformed

    private void jButton_SuaCTGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaCTGGActionPerformed

        int i = jTable_DanhSachCTGG.getSelectedRow();

        if (jTextField_TenCTGG.getText().trim().equals("") || jTextField_NoiDung.getText().trim().equals("") || jTextField_DieuKien.getText().trim().equals("") || jTextField_NgayNhap.getDate().equals("") || jTextField_NgayNhap1.getDate().equals("") || jTextField_Loai.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được bỏ trống");

        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String addDateBD = dateFormat.format(jTextField_NgayNhap.getDate());
            String addDateKT = dateFormat.format(jTextField_NgayNhap1.getDate());
            CtKm km = new CtKm(jTextField_MaGiamGia.getText(), jTextField_TenCTGG.getText(), jTextField_Loai.getText(), addDateBD, addDateKT, jTextField_NoiDung.getText(), jTextField_DieuKien.getText());
            try {
                boolean x = buss.updateCTKM(km);
                if (x) {
                    JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
                    loadData(buss.getCtKms());
                }
            } catch (SQLException ex) {
                Logger.getLogger(CTKM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton_SuaCTGGActionPerformed
String id_click = null;
    private void jTable_DanhSachCTGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhSachCTGGMouseClicked
        int i = jTable_DanhSachCTGG.getSelectedRow();
        jTextField_DieuKien.setText(buss.getdCtkm().get(i).getDieukien());
        jTextField_Loai.setText(buss.getdCtkm().get(i).getLoai());
        jTextField_MaGiamGia.setText(buss.getdCtkm().get(i).getMaMK());
        Date addDate = null;
        Date addDate1 = null;
        try {
         Date dateIn = new SimpleDateFormat("yyyy-MM-dd").parse((String)  buss.getdCtkm().get(i).getThoigianBD());
            jTextField_NgayNhap.setDate(dateIn);
            Date dateOut = new SimpleDateFormat("yyyy-MM-dd").parse((String) buss.getdCtkm().get(i).getThoigianKT());
            jTextField_NgayNhap1.setDate(dateOut);
        } catch (ParseException ex) {

        }
        jTextField_NoiDung.setText(buss.getdCtkm().get(i).getNoidung());
        jTextField_TenCTGG.setText(buss.getdCtkm().get(i).getTenCT());
        Random ran = new Random();
        int code = ran.nextInt((9999-1000)+1)+1000;
        jTextField_masp.setText(jTextField_Loai.getText()+String.valueOf(code));
        try {
            loadDataCT(buss.getCTCtKms(buss.getdCtkm().get(i).getMaMK()));
            id_click = buss.getdCtkm().get(i).getMaMK();
            jTextField_MagiamgiaCT1.setText(id_click);
        } catch (SQLException ex) {
            Logger.getLogger(CTKM.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTable_DanhSachCTGGMouseClicked

    private void jButton_XoaCTGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaCTGGActionPerformed

        
        int i = jTable_DanhSachCTGG.getSelectedRow();
        
        boolean x = false;
        try {
            x = buss.deleteCTKM(Integer.parseInt(jTextField_MaGiamGia.getText()));
//            System.out.println(x);
             if(x){
                JOptionPane.showMessageDialog(rootPane,"Xóa thành công");
            try {
                loadData(buss.getCtKms());
            } catch (SQLException ex) {
                Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        
        }

    }//GEN-LAST:event_jButton_XoaCTGGActionPerformed

    private void jButton_ResetCTGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetCTGGActionPerformed

//        jTextField_DieuKien.setText("");
        jTextField_Loai.setText("");
        jTextField_NoiDung.setText("");
        jTextField_TenCTGG.setText("");
        jTextField_MaGiamGia.setText("");
//        jTextField_NgayNhap.setDate(date);


    }//GEN-LAST:event_jButton_ResetCTGGActionPerformed

    private void jButton_ThemCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemCTActionPerformed

        int i = jTable_DanhSachCTGG.getSelectedRow();

        if (jTextField_MagiamgiaCT1.getText().trim().equals("") || jTextField_HInhThucCT1.getText().trim().equals("") || jTextField_masp.getText().equals("") ) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được bỏ trống");

        } else {
            
            CT_ctkm km = new CT_ctkm(String.valueOf(jTextField_MagiamgiaCT1.getText()),String.valueOf(jTextField_masp.getText()), jTextField_HInhThucCT1.getText());
            try {
                boolean x = buss.insertCTKM_CT(km);
                if (x) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                    loadDataCT(buss.getCTCtKms(id_click));
                }
            } catch (SQLException ex) {
                Logger.getLogger(CTKM.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CTKM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    

    }//GEN-LAST:event_jButton_ThemCTActionPerformed

    private void jButton_SuaCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaCTActionPerformed

         int i = jTable_DanhSachCTGG.getSelectedRow();

       if (jTextField_MagiamgiaCT1.getText().trim().equals("") || jTextField_HInhThucCT1.getText().trim().equals("") || jTextField_masp.getText().equals("") ) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được bỏ trống");

        }else {
            System.out.println();
            CT_ctkm km = new CT_ctkm(String.valueOf(jTextField_MaGiamGiaCT.getText()),String.valueOf(jTextField_masp.getText()),String.valueOf(jTextField_MagiamgiaCT1.getText()), jTextField_HInhThucCT1.getText());
            try {
                boolean x = buss.updateCTKM_CT(km);
                if (x) {
                    JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
                    loadDataCT(buss.getCTCtKms(id_click));
                }
            } catch (SQLException ex) {
                Logger.getLogger(CTKM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton_SuaCTActionPerformed

    private void jTable_ChiTietCTGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ChiTietCTGGMouseClicked

        int i = jTable_ChiTietCTGG.getSelectedRow();
        jTextField_MaGiamGiaCT.setText(tablemodel1.getValueAt(i,1).toString());
        jTextField_MagiamgiaCT1.setText(tablemodel1.getValueAt(i,3).toString());
        jTextField_masp.setText(tablemodel1.getValueAt(i,2).toString());
        jTextField_HInhThucCT1.setText(tablemodel1.getValueAt(i,4).toString());
        
    }//GEN-LAST:event_jTable_ChiTietCTGGMouseClicked

    private void jTextField_maspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_maspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_maspActionPerformed

    private void jButton_XoaCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaCTActionPerformed

        
        int i = jTable_ChiTietCTGG.getSelectedRow();
        
        boolean x = false;
        try {
            x = buss.deleteCTKM_CT(Integer.parseInt(jTextField_MaGiamGiaCT.getText()));
//            System.out.println(x);
             if(x){
                JOptionPane.showMessageDialog(rootPane,"Xóa thành công");
            try {
                loadDataCT(buss.getCTCtKms(id_click));
            } catch (SQLException ex) {
                Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        
        }

    }//GEN-LAST:event_jButton_XoaCTActionPerformed

    private void jButton_ResetCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetCTActionPerformed

//        jTextField_MaGiamGiaCT.setText("");
//        jTextField_MagiamgiaCT1.setText("");
        jTextField_HInhThucCT1.setText("");
//        jTextField_masp.setText("");

    }//GEN-LAST:event_jButton_ResetCTActionPerformed
    private void loadData() throws SQLException {
        ArrayList<CtKm> ds = new ArrayList<>();
        ds = buss.getCtKms();
        tablemodel.setRowCount(0);
        int i = 1;
        for (CtKm km : ds) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(km.getMaMK());
            vctData.add(km.getTenCT());
            vctData.add(km.getLoai());
            vctData.add(km.getThoigianBD());
            vctData.add(km.getThoigianKT());
            vctData.add(km.getNoidung());
            vctData.add(km.getDieukien());

            tablemodel.addRow(vctData);

        }
    }

    private void loadData(ArrayList<CtKm> ds) {
        tablemodel.setRowCount(0);
        int i = 1;
        for (CtKm km : ds) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(km.getMaMK());
            vctData.add(km.getTenCT());
            vctData.add(km.getLoai());
            vctData.add(km.getThoigianBD());
            vctData.add(km.getThoigianKT());
            vctData.add(km.getNoidung());
            vctData.add(km.getDieukien());

            tablemodel.addRow(vctData);

        }
    }
    private void loadDataCT(ArrayList<CT_ctkm> ds) {
        tablemodel1.setRowCount(0);
        int i = 1;
        for (CT_ctkm km : ds) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(km.getCt_ctkmID());
            vctData.add(km.getCtkmID());
            vctData.add(km.getSanphamID());
            vctData.add(km.getHinhthuc());
            tablemodel1.addRow(vctData);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTKM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTKM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTKM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTKM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTKM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ResetCT;
    private javax.swing.JButton jButton_ResetCTGG;
    private javax.swing.JButton jButton_SuaCT;
    private javax.swing.JButton jButton_SuaCTGG;
    private javax.swing.JButton jButton_ThemCT;
    private javax.swing.JButton jButton_ThemCTGG;
    private javax.swing.JButton jButton_XoaCT;
    private javax.swing.JButton jButton_XoaCTGG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_ChiTietCTGG;
    private javax.swing.JTable jTable_DanhSachCTGG;
    private javax.swing.JTextField jTextField_DieuKien;
    private javax.swing.JTextField jTextField_HInhThucCT1;
    private javax.swing.JTextField jTextField_Loai;
    private javax.swing.JTextField jTextField_MaGiamGia;
    private javax.swing.JTextField jTextField_MaGiamGiaCT;
    private javax.swing.JTextField jTextField_MagiamgiaCT1;
    private com.toedter.calendar.JDateChooser jTextField_NgayNhap;
    private com.toedter.calendar.JDateChooser jTextField_NgayNhap1;
    private javax.swing.JTextField jTextField_NoiDung;
    private javax.swing.JTextField jTextField_TenCTGG;
    private javax.swing.JTextField jTextField_masp;
    // End of variables declaration//GEN-END:variables
}
