/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.Buss;
import DTO.KhachHang;
import DTO.PhieuNhap;
import DTO.Ncc;
import GUI.ChiTietPhieuNhap;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KHANH
 */
public class PhieuNhap3 extends javax.swing.JFrame {

    /**
     * Creates new form PhieuNhap3
     */
      DefaultTableModel tablemodel;
      DefaultTableModel tablemodel1;
    Buss buss ;
    public PhieuNhap3() throws SQLException {
        initComponents();
        buss = new Buss();
        tablemodel = (DefaultTableModel) jTable_PhieuNhap.getModel();
        tablemodel1 = (DefaultTableModel) jTable_NhaCungCap.getModel();
        loadDataNcc();
        loadDataPN();
        loadComboxNV();
        loadComboxNcc();
    }
    
    private void loadDataNcc() throws SQLException {
        ArrayList<Ncc> ds = new ArrayList<>();
        ds = buss.getNccs();
        tablemodel1.setRowCount(0);
        int i = 1;
        for (Ncc kh : ds) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(kh.getNccID());
            vctData.add(kh.getNccName());
            vctData.add(kh.getSdt());
            vctData.add(kh.getEmail());
            vctData.add(kh.getDiachi());
            tablemodel1.addRow(vctData);

        }
    }

    private void loadDataNcc(ArrayList<Ncc> dskh) {
        tablemodel1.setRowCount(0);
        int i = 1;
        for (Ncc kh : dskh) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(kh.getNccID());
            vctData.add(kh.getNccName());
            vctData.add(kh.getSdt());
            vctData.add(kh.getEmail());
            vctData.add(kh.getDiachi());
            tablemodel1.addRow(vctData);

        }
    }
    private void loadDataPN() throws SQLException {
        ArrayList<PhieuNhap> ds = new ArrayList<>();
        ds = buss.getPhieuNhaps();
        tablemodel.setRowCount(0);
        int i = 1;
        for (PhieuNhap kh : ds) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(kh.getMaPN());
            vctData.add(kh.getMaNV());
            System.out.println(kh.getMaNV());
            vctData.add(kh.getMaNCC());
            vctData.add(kh.getTongTien());
            vctData.add(kh.getNgayNhap());
            tablemodel.addRow(vctData);

        }
    }

    private void loadDataPhieuNhap(ArrayList<PhieuNhap> ds) {
        tablemodel.setRowCount(0);
        int i = 1;
        for (PhieuNhap kh : ds) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(kh.getMaPN());
            vctData.add(kh.getMaNV());
            vctData.add(kh.getMaNCC());
            vctData.add(kh.getTongTien());
            vctData.add(kh.getNgayNhap());
            tablemodel.addRow(vctData);

        }
    }

    private ArrayList<Ncc> findma(String ma) throws SQLException {
        return buss.findMaNcc(ma);
    }

    private ArrayList<Ncc> findTen(String ho) throws SQLException {
        return buss.findtenNCC(ho);
    }

    private ArrayList<Ncc> findsdtNcc(String phone) throws SQLException {
        return buss.findphoneNcc(phone);
    }
    private ArrayList<Ncc> findEmailNcc(String phone) throws SQLException {
        return buss.findEmailNcc(phone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_PhieuNhap = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ID_PN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_TongTien_PN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_NCC_PN = new javax.swing.JComboBox<>();
        jDateChooser_NgayNhap_PN = new com.toedter.calendar.JDateChooser();
        jButton_Them_PN = new javax.swing.JButton();
        jButton_NhapHang_PN = new javax.swing.JButton();
        jButton_Sua_PN = new javax.swing.JButton();
        jButton_Xoa_PN = new javax.swing.JButton();
        jButton_NhapLai_PN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_TimKiem_PN = new javax.swing.JTextField();
        jComboBox_TimKiem_PN = new javax.swing.JComboBox<>();
        jButton_TimKiem_PN = new javax.swing.JButton();
        jComboBox_NCC_PN1 = new javax.swing.JComboBox<>();
        jButton_TatCa1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_NhaCungCap = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextField_ID_NCC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Ten_NCC = new javax.swing.JTextField();
        jTextField_SDT_NCC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Email_NCC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_TimKiem_NCC = new javax.swing.JComboBox<>();
        jButton_NhapLai_NCC = new javax.swing.JButton();
        jButton_Tim_NCC = new javax.swing.JButton();
        jTextField_DiaChi_NCC = new javax.swing.JTextField();
        jTextField_TimKiem_NCC = new javax.swing.JTextField();
        jButton_Sua_NCC = new javax.swing.JButton();
        jButton_Xoa_NCC = new javax.swing.JButton();
        jButton_Them_NCC = new javax.swing.JButton();
        jButton_TatCa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHIẾU NHẬP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        jTable_PhieuNhap.setBackground(new java.awt.Color(153, 255, 255));
        jTable_PhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số thứ tự", "Mã phiếu nhập", "Mã nhân viên", "Nhà cung cấp", "Tổng tiền", "Ngày nhập"
            }
        ));
        jTable_PhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_PhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_PhieuNhap);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã phiếu nhập");

        jTextField_ID_PN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_ID_PN.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã nhân viên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nhà cung cấp");

        jTextField_TongTien_PN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tổng tiền");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ngày nhập");

        jComboBox_NCC_PN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jDateChooser_NgayNhap_PN.setDateFormatString("dd/MM/yyyy");

        jButton_Them_PN.setBackground(new java.awt.Color(153, 255, 153));
        jButton_Them_PN.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_Them_PN.setText("Thêm");
        jButton_Them_PN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Them_PNActionPerformed(evt);
            }
        });

        jButton_NhapHang_PN.setBackground(new java.awt.Color(255, 255, 102));
        jButton_NhapHang_PN.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_NhapHang_PN.setText("Nhập hàng");
        jButton_NhapHang_PN.setEnabled(false);
        jButton_NhapHang_PN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NhapHang_PNActionPerformed(evt);
            }
        });

        jButton_Sua_PN.setBackground(new java.awt.Color(102, 153, 255));
        jButton_Sua_PN.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_Sua_PN.setText("Sửa");
        jButton_Sua_PN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sua_PNActionPerformed(evt);
            }
        });

        jButton_Xoa_PN.setBackground(new java.awt.Color(255, 102, 102));
        jButton_Xoa_PN.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_Xoa_PN.setText("Xóa");
        jButton_Xoa_PN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Xoa_PNActionPerformed(evt);
            }
        });

        jButton_NhapLai_PN.setBackground(new java.awt.Color(204, 204, 204));
        jButton_NhapLai_PN.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_NhapLai_PN.setText("Nhập lại");
        jButton_NhapLai_PN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NhapLai_PNActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tìm kiếm");

        jTextField_TimKiem_PN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jComboBox_TimKiem_PN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_TimKiem_PN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã phiếu nhập", "Mã nhân viên", "Nhà cung cấp" }));

        jButton_TimKiem_PN.setBackground(new java.awt.Color(204, 255, 255));
        jButton_TimKiem_PN.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_TimKiem_PN.setText("Tìm");
        jButton_TimKiem_PN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiem_PNActionPerformed(evt);
            }
        });

        jComboBox_NCC_PN1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_TatCa1.setBackground(new java.awt.Color(204, 255, 255));
        jButton_TatCa1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_TatCa1.setText("Tất cả");
        jButton_TatCa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TatCa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField_TimKiem_PN))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField_ID_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_NCC_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_NCC_PN1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_TongTien_PN, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(jDateChooser_NgayNhap_PN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jComboBox_TimKiem_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Them_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_NhapHang_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Sua_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Xoa_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_NhapLai_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(177, 177, 177))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton_TimKiem_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_TatCa1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ID_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Them_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_NhapHang_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_NCC_PN1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Sua_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_NCC_PN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TongTien_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Xoa_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jDateChooser_NgayNhap_PN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton_NhapLai_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TimKiem_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_TimKiem_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TimKiem_PN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TatCa1))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Phiếu nhập", jPanel3);

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));

        jTable_NhaCungCap.setBackground(new java.awt.Color(153, 255, 255));
        jTable_NhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số thứ tự", "Mã nhà cung cấp", "Tên nhà cung cấp", "Số điện thoại", "Email", "Địa chỉ"
            }
        ));
        jTable_NhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_NhaCungCapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_NhaCungCap);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Mã nhà cung cấp");

        jTextField_ID_NCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_ID_NCC.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tên nhà cung cấp");

        jTextField_Ten_NCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_SDT_NCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Số điện thoại");

        jTextField_Email_NCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Email");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Địa chỉ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Tìm kiếm");

        jComboBox_TimKiem_NCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_TimKiem_NCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã nhà cung cấp", "Tên nhà cung cấp", "Số điện thoại", "Email" }));

        jButton_NhapLai_NCC.setBackground(new java.awt.Color(204, 204, 204));
        jButton_NhapLai_NCC.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_NhapLai_NCC.setText("Nhập lại");
        jButton_NhapLai_NCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NhapLai_NCCActionPerformed(evt);
            }
        });

        jButton_Tim_NCC.setBackground(new java.awt.Color(204, 255, 255));
        jButton_Tim_NCC.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_Tim_NCC.setText("Tìm");
        jButton_Tim_NCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tim_NCCActionPerformed(evt);
            }
        });

        jTextField_DiaChi_NCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_TimKiem_NCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton_Sua_NCC.setBackground(new java.awt.Color(51, 153, 255));
        jButton_Sua_NCC.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_Sua_NCC.setText("Sửa");
        jButton_Sua_NCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sua_NCCActionPerformed(evt);
            }
        });

        jButton_Xoa_NCC.setBackground(new java.awt.Color(255, 102, 102));
        jButton_Xoa_NCC.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_Xoa_NCC.setText("Xóa");
        jButton_Xoa_NCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Xoa_NCCActionPerformed(evt);
            }
        });

        jButton_Them_NCC.setBackground(new java.awt.Color(153, 255, 153));
        jButton_Them_NCC.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_Them_NCC.setText("Thêm");
        jButton_Them_NCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Them_NCCActionPerformed(evt);
            }
        });

        jButton_TatCa.setBackground(new java.awt.Color(204, 255, 255));
        jButton_TatCa.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_TatCa.setText("Tất cả");
        jButton_TatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TatCaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_TimKiem_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_DiaChi_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_Email_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_SDT_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_Ten_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_ID_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addComponent(jComboBox_TimKiem_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Sua_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_NhapLai_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Xoa_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Them_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton_Tim_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton_TatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ID_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Them_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Ten_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Sua_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_SDT_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Xoa_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Email_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_NhapLai_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_DiaChi_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_TimKiem_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Tim_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TimKiem_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Nhà cung cấp", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_NhapLai_NCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NhapLai_NCCActionPerformed

        jTextField_DiaChi_NCC.setText("");
        jTextField_Email_NCC.setText("");
        jTextField_ID_NCC.setText("");
        jTextField_SDT_NCC.setText("");
        jTextField_Ten_NCC.setText("");

    }//GEN-LAST:event_jButton_NhapLai_NCCActionPerformed

    private void jButton_Tim_NCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tim_NCCActionPerformed
        ArrayList<Ncc> ds = new ArrayList<>();
        int x = jComboBox_TimKiem_NCC.getSelectedIndex();
        switch (x) {
            case 1: {
                try {
                    ds = buss.findtenNCC(jTextField_TimKiem_NCC.getText());
                    loadDataNcc(ds);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            break;

            case 2: {
                try {
                    ds = buss.findphoneNcc(jTextField_TimKiem_NCC.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            loadDataNcc(ds);
//               dsfind.clear();
            break;

            case 3: {
                try {
                    ds = buss.findEmailNcc(jTextField_TimKiem_NCC.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            loadDataNcc(ds);
//               dsfind.clear();
            break;

            case 0: {
                 try {
                    ds = buss.findMaNcc(jTextField_TimKiem_NCC.getText());
                    loadDataNcc(ds);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;

        }


    }//GEN-LAST:event_jButton_Tim_NCCActionPerformed

    private void jButton_Sua_NCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sua_NCCActionPerformed

 if (jTextField_DiaChi_NCC.getText().trim().equals("") || jTextField_Email_NCC.getText().trim().equals("") || jTextField_SDT_NCC.getText().trim().equals("") || jTextField_Ten_NCC.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được bỏ trống");

        } else {
            try {
                
//                if (buss.checkSDTNcc(jTextField_SDT_NCC.getText())) 
                    Ncc ncc = new Ncc(jTextField_ID_NCC.getText(),jTextField_Ten_NCC.getText(), jTextField_SDT_NCC.getText(), jTextField_Email_NCC.getText(), jTextField_DiaChi_NCC.getText());
                    boolean x = buss.updateNcc(ncc);
                    if (x) {
                        JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
                        loadDataNcc();
                    }
//                } else {
//                    JOptionPane.showMessageDialog(rootPane, "Số Điện Thoại Đã tồn tại");
//
//                }
            } catch (SQLException ex) {
                Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_Sua_NCCActionPerformed

    private void jButton_Xoa_NCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Xoa_NCCActionPerformed

         int i = jTable_NhaCungCap.getSelectedRow();

        boolean x = false;
        try {
            x = buss.deleteNCc(Integer.parseInt(jTextField_ID_NCC.getText()));
            if (x) {
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                
                try {
                    loadDataNcc();
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Xoa_NCCActionPerformed

    private void jButton_Them_NCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Them_NCCActionPerformed

        
        if (jTextField_DiaChi_NCC.getText().trim().equals("") || jTextField_Email_NCC.getText().trim().equals("") || jTextField_SDT_NCC.getText().trim().equals("") || jTextField_Ten_NCC.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được bỏ trống");

        } else {
            try {
                
                if (buss.checkSDTNcc(jTextField_SDT_NCC.getText())) {
                    Ncc ncc = new Ncc(jTextField_Ten_NCC.getText(), jTextField_SDT_NCC.getText(), jTextField_Email_NCC.getText(), jTextField_DiaChi_NCC.getText());
                    boolean x = buss.insertNcc(ncc);
                    if (x) {
                        JOptionPane.showMessageDialog(rootPane, "Thêm thành  công");
                        loadDataNcc();
                        loadComboxNcc();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Số Điện Thoại Đã tồn tại");

                }
            } catch (SQLException ex) {
                Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Them_NCCActionPerformed

    private void jButton_NhapHang_PNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NhapHang_PNActionPerformed
                    // TODO add your handling code here:
        ChiTietPhieuNhap ctpn = null;
          try {
              ctpn = new ChiTietPhieuNhap(jTextField_ID_PN.getText());
          } catch (SQLException ex) {
              Logger.getLogger(PhieuNhap3.class.getName()).log(Level.SEVERE, null, ex);
          }
        ctpn.pack();
        ctpn.setLocationRelativeTo(null);
        ctpn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_NhapHang_PNActionPerformed

    private void jButton_Sua_PNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sua_PNActionPerformed

 SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String time = dateFormat.format(jDateChooser_NgayNhap_PN.getDate());
         if ( time.trim().equals("") ) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được bỏ trống");

        } else {
            try {
               
                    PhieuNhap kh = new PhieuNhap(jTextField_ID_PN.getText(),String.valueOf(jComboBox_NCC_PN1.getSelectedItem()),String.valueOf(jComboBox_NCC_PN.getSelectedItem()),jTextField_TongTien_PN.getText(),time);
                    boolean x = buss.updatePhieuNhap(kh);
                    if (x) {
                        JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
                        loadDataPN();
                    }
               
            } catch (SQLException ex) {
                Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_Sua_PNActionPerformed

    private void jButton_TatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TatCaActionPerformed

          try {
              loadDataNcc();
          } catch (SQLException ex) {
              Logger.getLogger(PhieuNhap3.class.getName()).log(Level.SEVERE, null, ex);
          }

    }//GEN-LAST:event_jButton_TatCaActionPerformed

    private void jButton_TatCa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TatCa1ActionPerformed

          try {
              loadDataPN();
              // TODO add your handling code here:
          } catch (SQLException ex) {
              Logger.getLogger(PhieuNhap3.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jButton_TatCa1ActionPerformed

    private void jTable_NhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_NhaCungCapMouseClicked

        
        int i = jTable_NhaCungCap.getSelectedRow();
        jTextField_DiaChi_NCC.setText(buss.getDsNcc().get(i).getDiachi());
        jTextField_Ten_NCC.setText(buss.getDsNcc().get(i).getNccName());
        jTextField_SDT_NCC.setText(buss.getDsNcc().get(i).getSdt());
        jTextField_Email_NCC.setText(buss.getDsNcc().get(i).getEmail());
        jTextField_ID_NCC.setText(buss.getDsNcc().get(i).getNccID());


    }//GEN-LAST:event_jTable_NhaCungCapMouseClicked

    private void jButton_Them_PNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Them_PNActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String time = dateFormat.format(jDateChooser_NgayNhap_PN.getDate());
         if (time.trim().equals("") ) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được bỏ trống");
        } else {
            try {
               
                    PhieuNhap kh = new PhieuNhap(String.valueOf(jComboBox_NCC_PN1.getSelectedItem()),String.valueOf(jComboBox_NCC_PN.getSelectedItem()),jTextField_TongTien_PN.getText(),time);
                    boolean x = buss.insertPhieuNhap(kh);
                    if (x) {
                        JOptionPane.showMessageDialog(rootPane, "Thêm thành  công");
                        loadDataPN();
                    }
               
            } catch (SQLException ex) {
                Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton_Them_PNActionPerformed
    private void loadComboxNV() throws SQLException{
        ResultSet rs = null;
        rs = buss.loadComboxNVBH();
        Vector v = new Vector();
        while(rs.next()){
            v.add(rs.getString("nvID"));
            
            DefaultComboBoxModel com = new DefaultComboBoxModel(v);
            jComboBox_NCC_PN1.setModel(com);
        }
    }
    private void loadComboxNcc() throws SQLException{
        ResultSet rs = null;
        rs = buss.loadComboxNcc();
        Vector v = new Vector();
        while(rs.next()){
            v.add(rs.getString("nccID"));
            DefaultComboBoxModel com = new DefaultComboBoxModel(v);
            jComboBox_NCC_PN.setModel(com);
        }
    }
    private void jButton_Xoa_PNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Xoa_PNActionPerformed

        
        int i = jTable_PhieuNhap.getSelectedRow();

        boolean x = false;
          try {
              x = buss.deletePhieuNhap(jTextField_ID_PN.getText()); // TODO add your handling code here:
          } catch (SQLException ex) {
              Logger.getLogger(PhieuNhap3.class.getName()).log(Level.SEVERE, null, ex);
          }
        if (x) {
            JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
            try {
                loadDataPN();
            } catch (SQLException ex) {
                Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_Xoa_PNActionPerformed

    private void jTable_PhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_PhieuNhapMouseClicked

        int i =jTable_PhieuNhap.getSelectedRow();
        jTextField_ID_PN.setText(buss.getDsPhieuNhap().get(i).getMaPN());
        jComboBox_NCC_PN.setSelectedItem(buss.getDsPhieuNhap().get(i).getMaNV());
        jComboBox_NCC_PN1.setSelectedItem(buss.getDsPhieuNhap().get(i).getMaNCC());
        jTextField_TongTien_PN.setText(buss.getDsPhieuNhap().get(i).getTongTien());
        try {
         Date dateIn = new SimpleDateFormat("yyyy-MM-dd").parse((String)  buss.getDsPhieuNhap().get(i).getNgayNhap());
            jDateChooser_NgayNhap_PN.setDate(dateIn);
            
        } catch (ParseException ex) {

        }
        jButton_NhapHang_PN.setEnabled(true);
        
        
    }//GEN-LAST:event_jTable_PhieuNhapMouseClicked

    private void jButton_NhapLai_PNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NhapLai_PNActionPerformed

        jTextField_ID_PN.setText("");
        jButton_NhapHang_PN.setEnabled(false);
        jComboBox_NCC_PN.setSelectedIndex(0);
        jComboBox_NCC_PN1.setSelectedIndex(0);
        jTextField_TongTien_PN.setText("");
        
        
    }//GEN-LAST:event_jButton_NhapLai_PNActionPerformed

    private void jButton_TimKiem_PNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiem_PNActionPerformed
        ArrayList<PhieuNhap> ds = new ArrayList<>();
        int i = jComboBox_TimKiem_PN.getSelectedIndex();
        switch(i){
            case 0:
                try {
                    ds = buss.findMaPhieuNhap(jTextField_TimKiem_NCC.getText());
                    loadDataPhieuNhap(ds);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case 1:
                try {
                    ds = buss.findMaNV(jTextField_TimKiem_NCC.getText());
                    loadDataPhieuNhap(ds);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case 2:
                try {
                    ds = buss.findMaNCC(jTextField_TimKiem_NCC.getText());
                    loadDataPhieuNhap(ds);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
        }

    }//GEN-LAST:event_jButton_TimKiem_PNActionPerformed
boolean tt = true;
    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        
        if(tt){
            jLabel1.setText("Nhà Cung Cấp");
        }else{
            jLabel1.setText("Phiếu Nhập");
        }
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuNhap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuNhap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuNhap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuNhap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PhieuNhap3().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PhieuNhap3.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_NhapHang_PN;
    private javax.swing.JButton jButton_NhapLai_NCC;
    private javax.swing.JButton jButton_NhapLai_PN;
    private javax.swing.JButton jButton_Sua_NCC;
    private javax.swing.JButton jButton_Sua_PN;
    private javax.swing.JButton jButton_TatCa;
    private javax.swing.JButton jButton_TatCa1;
    private javax.swing.JButton jButton_Them_NCC;
    private javax.swing.JButton jButton_Them_PN;
    private javax.swing.JButton jButton_TimKiem_PN;
    private javax.swing.JButton jButton_Tim_NCC;
    private javax.swing.JButton jButton_Xoa_NCC;
    private javax.swing.JButton jButton_Xoa_PN;
    private javax.swing.JComboBox<String> jComboBox_NCC_PN;
    private javax.swing.JComboBox<String> jComboBox_NCC_PN1;
    private javax.swing.JComboBox<String> jComboBox_TimKiem_NCC;
    private javax.swing.JComboBox<String> jComboBox_TimKiem_PN;
    private com.toedter.calendar.JDateChooser jDateChooser_NgayNhap_PN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_NhaCungCap;
    private javax.swing.JTable jTable_PhieuNhap;
    private javax.swing.JTextField jTextField_DiaChi_NCC;
    private javax.swing.JTextField jTextField_Email_NCC;
    private javax.swing.JTextField jTextField_ID_NCC;
    private javax.swing.JTextField jTextField_ID_PN;
    private javax.swing.JTextField jTextField_SDT_NCC;
    private javax.swing.JTextField jTextField_Ten_NCC;
    private javax.swing.JTextField jTextField_TimKiem_NCC;
    private javax.swing.JTextField jTextField_TimKiem_PN;
    private javax.swing.JTextField jTextField_TongTien_PN;
    // End of variables declaration//GEN-END:variables
}
