/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.Buss;
import BUS.importData;
import DAL.ConnectSQL;
import DTO.HoaDon;
import DTO.KhachHang;
import com.itextpdf.text.DocumentException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class QuanLiKhachHang extends javax.swing.JFrame {

    DefaultTableModel tablemodel;
    Buss buss = new Buss();
//    DataBase dataBase;
//    DsKhachHang ds;

    /**
     * Creates new form index
     */
    public QuanLiKhachHang() throws SQLException {
        initComponents();
        tablemodel = (DefaultTableModel) jTable_QLKH.getModel();
        loadData();

    }

    private void loadData() throws SQLException {
//        dskh = ConnectSQL.getKhachHangs();
        ArrayList<KhachHang> ds = new ArrayList<>();
        ds = buss.getKhachHangs();
        tablemodel.setRowCount(0);
        int i = 1;
        String gioitinh;
        for (KhachHang kh : ds) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(kh.getId());
            vctData.add(kh.getHo());
            vctData.add(kh.getTen());
            vctData.add(kh.getDiachi());
            vctData.add(kh.getPhone());
//            vctData.add(kh.isGioitinh());
            if (kh.isGioitinh()) {
                gioitinh = "Nam";
            } else {
                gioitinh = "Nữ";
            }

            vctData.add(gioitinh);
//            vctData.add(kh.getDia_chi());

            tablemodel.addRow(vctData);

        }
    }

    private void loadData(ArrayList<KhachHang> dskh) {
        tablemodel.setRowCount(0);
        int i = 1;
        String gioitinh;
        for (KhachHang kh : dskh) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(kh.getId());
            vctData.add(kh.getHo());
            vctData.add(kh.getTen());
            vctData.add(kh.getDiachi());
            vctData.add(kh.getPhone());
            if (kh.isGioitinh()) {
                gioitinh = "Nam";
            } else {
                gioitinh = "Nữ";
            }

            vctData.add(gioitinh);

            tablemodel.addRow(vctData);

        }
    }

    private ArrayList<KhachHang> findSv(int mssv) throws SQLException {
        return buss.findMa1(mssv);
    }

    private ArrayList<KhachHang> findHo(String ho) throws SQLException {
        return buss.findHo(ho);
    }

    private ArrayList<KhachHang> findTen(String ten) throws SQLException {
        return buss.findTen(ten);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_GioiTinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Ten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_SoDienThoai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Ho = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_DiaChi = new javax.swing.JTextField();
        jRadioButton_Nam = new javax.swing.JRadioButton();
        jRadioButton_Nu = new javax.swing.JRadioButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Sua1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField_idkh = new javax.swing.JTextField();
        jButton_them = new javax.swing.JButton();
        jButton_lapgiohang = new javax.swing.JButton();
        jButton_them1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_QLKH = new javax.swing.JTable();
        jTextField_TimKiem = new javax.swing.JTextField();
        jComboBox_TimKiem = new javax.swing.JComboBox<>();
        jButton_TimKiem = new javax.swing.JButton();
        jButton_HienThi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý khách hàng");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 1, true), "Sửa thông tin khách hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(191, 168, 111))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên");

        jTextField_Ten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Ten.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 195, 95), 1, true));
        jTextField_Ten.setSelectionColor(new java.awt.Color(232, 181, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Số điện thoại");

        jTextField_SoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_SoDienThoai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 195, 95), 1, true));
        jTextField_SoDienThoai.setSelectionColor(new java.awt.Color(232, 181, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Họ và tên đệm");

        jTextField_Ho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Ho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 195, 95), 1, true));
        jTextField_Ho.setSelectionColor(new java.awt.Color(232, 181, 20));
        jTextField_Ho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_HoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Địa chỉ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Giới tính");

        jTextField_DiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_DiaChi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 195, 95), 1, true));
        jTextField_DiaChi.setSelectionColor(new java.awt.Color(232, 181, 20));

        buttonGroup_GioiTinh.add(jRadioButton_Nam);
        jRadioButton_Nam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_Nam.setText("Nam");

        buttonGroup_GioiTinh.add(jRadioButton_Nu);
        jRadioButton_Nu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_Nu.setText("Nữ");
        jRadioButton_Nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_NuActionPerformed(evt);
            }
        });

        jButton_Sua.setBackground(new java.awt.Color(255, 252, 246));
        jButton_Sua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });

        jButton_Sua1.setBackground(new java.awt.Color(255, 252, 246));
        jButton_Sua1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Sua1.setText("Xóa");
        jButton_Sua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sua1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("ID Khách hàng");

        jTextField_idkh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_idkh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 195, 95), 1, true));
        jTextField_idkh.setEnabled(false);
        jTextField_idkh.setSelectionColor(new java.awt.Color(232, 181, 20));
        jTextField_idkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idkhActionPerformed(evt);
            }
        });

        jButton_them.setBackground(new java.awt.Color(255, 252, 246));
        jButton_them.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_them.setText("Thêm");
        jButton_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_themActionPerformed(evt);
            }
        });

        jButton_lapgiohang.setBackground(new java.awt.Color(255, 252, 246));
        jButton_lapgiohang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_lapgiohang.setText("Lập Hóa Đơn");
        jButton_lapgiohang.setEnabled(false);
        jButton_lapgiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lapgiohangActionPerformed(evt);
            }
        });

        jButton_them1.setBackground(new java.awt.Color(255, 252, 246));
        jButton_them1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_them1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Refresh.png"))); // NOI18N
        jButton_them1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_them1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_idkh, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_them1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton_them, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_lapgiohang, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Sua1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_Nu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Ho, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Ten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_SoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_Nu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Sua1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_them, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_lapgiohang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_idkh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_them1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Ho, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 1, true), "Tìm kiếm thông tin khách hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(190, 162, 90))); // NOI18N

        jTable_QLKH.setBackground(new java.awt.Color(255, 247, 232));
        jTable_QLKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_QLKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID khách hàng", "Họ", "Tên", "Địa chỉ", "Số điện thoại", "Giới tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_QLKH.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_QLKH.setSelectionBackground(new java.awt.Color(249, 228, 197));
        jTable_QLKH.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable_QLKH.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTable_QLKH.setShowVerticalLines(false);
        jTable_QLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_QLKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_QLKH);
        if (jTable_QLKH.getColumnModel().getColumnCount() > 0) {
            jTable_QLKH.getColumnModel().getColumn(4).setResizable(false);
            jTable_QLKH.getColumnModel().getColumn(5).setResizable(false);
        }

        jTextField_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_TimKiem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 195, 95), 1, true));
        jTextField_TimKiem.setSelectionColor(new java.awt.Color(232, 181, 20));

        jComboBox_TimKiem.setBackground(new java.awt.Color(255, 252, 246));
        jComboBox_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_TimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Số điện thoại", "Họ", "Tên", "Mã Khách Hàng" }));
        jComboBox_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TimKiemActionPerformed(evt);
            }
        });

        jButton_TimKiem.setBackground(new java.awt.Color(255, 224, 156));
        jButton_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_TimKiem.setText("Tìm kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });

        jButton_HienThi.setBackground(new java.awt.Color(255, 252, 246));
        jButton_HienThi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_HienThi.setText("Hiển thị tất cả");
        jButton_HienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HienThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jComboBox_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_TimKiem)
                        .addGap(15, 15, 15)
                        .addComponent(jButton_HienThi)
                        .addGap(0, 273, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_TimKiem)
                        .addComponent(jButton_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_HienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(226, 178, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_HoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_HoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_HoActionPerformed

    private void jRadioButton_NuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_NuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_NuActionPerformed

    private void jButton_HienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HienThiActionPerformed

        try {
            loadData();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_HienThiActionPerformed

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        ArrayList<KhachHang> ds = new ArrayList<>();
        int x = jComboBox_TimKiem.getSelectedIndex();
        System.out.println(x);
        switch (x) {
            case 1: {
                try {
                    ds = buss.findHo(jTextField_TimKiem.getText());
                    loadData(ds);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            break;

            case 2: {
                try {
                    ds = buss.findTen(jTextField_TimKiem.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            loadData(ds);
//               dsfind.clear();
            break;

            case 3: {
                try {
                    ds = buss.findMa1(Integer.parseInt(jTextField_TimKiem.getText()));
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            loadData(ds);
//               dsfind.clear();
            break;

            case 0: {
                try {
                    ds = buss.findphone(jTextField_TimKiem.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            loadData(ds);
            break;

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    private void jComboBox_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TimKiemActionPerformed

    private void jTable_QLKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_QLKHMouseClicked

        int i = jTable_QLKH.getSelectedRow();
        jTextField_DiaChi.setText(buss.getDskh().get(i).getDiachi());
        jTextField_Ho.setText(buss.getDskh().get(i).getHo());
        jTextField_Ten.setText(buss.getDskh().get(i).getTen());
        jTextField_SoDienThoai.setText(buss.getDskh().get(i).getPhone());
        jTextField_idkh.setText(String.valueOf(buss.getDskh().get(i).getId()));

        if (buss.getDskh().get(i).isGioitinh()) {
            jRadioButton_Nam.setSelected(true);
        } else {
            jRadioButton_Nu.setSelected(true);
        }
        jButton_lapgiohang.setEnabled(true);

    }//GEN-LAST:event_jTable_QLKHMouseClicked

    private void jTextField_idkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idkhActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed

        int i = jTable_QLKH.getSelectedRow();
        boolean gt = false;
        if (jRadioButton_Nam.isSelected()) {
            gt = true;
        }
        if (jTextField_Ten.getText().trim().equals("") || jTextField_SoDienThoai.getText().trim().equals("") || jTextField_DiaChi.getText().trim().equals("") || jTextField_Ho.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được bỏ trống");

        } else {
            try {
                if (buss.checkSDTKH(jTextField_SoDienThoai.getText())) {
                    KhachHang kh = new KhachHang(Integer.parseInt(jTextField_idkh.getText()), jTextField_Ho.getText(), jTextField_Ten.getText(), jTextField_DiaChi.getText(), jTextField_SoDienThoai.getText(), gt);
                    buss.getDskh().get(i).update(jTextField_Ho.getText(), jTextField_Ten.getText(), jTextField_DiaChi.getText(), jTextField_SoDienThoai.getText(), gt);
                    try {
                        loadData();
                    } catch (SQLException ex) {
                        Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        boolean x = buss.updateKH(kh);
                        if (x) {
                            JOptionPane.showMessageDialog(rootPane, "Cập nhật thành  công");
                            loadData();
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Số Điện Thoại đã tồn tại");

                }
            } catch (SQLException ex) {
                Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_Sua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sua1ActionPerformed

        int i = jTable_QLKH.getSelectedRow();

        boolean x = false;
        try {
            x = buss.deleteKH(Integer.parseInt(jTextField_idkh.getText()));
            if (x) {
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                buss.getDskh().remove(i);
                try {
                    loadData();
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton_Sua1ActionPerformed

    private void jButton_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_themActionPerformed

        if (jTextField_Ten.getText().trim().equals("") || jTextField_SoDienThoai.getText().trim().equals("") || jTextField_DiaChi.getText().trim().equals("") || jTextField_Ho.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được bỏ trống");

        } else {
            try {
                boolean gt = false;
                if (jRadioButton_Nam.isSelected()) {
                    gt = true;
                }
                if (buss.checkSDTKH(jTextField_SoDienThoai.getText())) {
                    KhachHang kh = new KhachHang(jTextField_Ho.getText(), jTextField_Ten.getText(), jTextField_DiaChi.getText(), jTextField_SoDienThoai.getText(), gt);
                    boolean x = buss.insertKhachHang(kh);
                    if (x) {
                        JOptionPane.showMessageDialog(rootPane, "Thêm thành  công");
                        loadData();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Số Điện Thoại Đã tồn tại");

                }
            } catch (SQLException ex) {
                Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jButton_themActionPerformed

    private void jButton_lapgiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lapgiohangActionPerformed

        HoaDonTam hd = new HoaDonTam(jTextField_idkh.getText());
        hd.pack();
        hd.setVisible(true);
        hd.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_lapgiohangActionPerformed

    private void jButton_them1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_them1ActionPerformed
        
        jTextField_idkh.setText("");
        jTextField_DiaChi.setText("");
        jTextField_Ho.setText("");
        jTextField_SoDienThoai.setText("");
        jTextField_Ten.setText("");
        jRadioButton_Nam.setSelected(true);
        jButton_lapgiohang.setEnabled(false);

    }//GEN-LAST:event_jButton_them1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QuanLiKhachHang().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_GioiTinh;
    private javax.swing.JButton jButton_HienThi;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Sua1;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_lapgiohang;
    private javax.swing.JButton jButton_them;
    private javax.swing.JButton jButton_them1;
    private javax.swing.JComboBox<String> jComboBox_TimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton_Nam;
    private javax.swing.JRadioButton jRadioButton_Nu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_QLKH;
    private javax.swing.JTextField jTextField_DiaChi;
    private javax.swing.JTextField jTextField_Ho;
    private javax.swing.JTextField jTextField_SoDienThoai;
    private javax.swing.JTextField jTextField_Ten;
    private javax.swing.JTextField jTextField_TimKiem;
    private javax.swing.JTextField jTextField_idkh;
    // End of variables declaration//GEN-END:variables
}
