/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.Buss;
import DTO.NhanVien;
import DTO.product;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.compress.utils.IOUtils;

/**
 *
 * @author ACER
 */
public class SanPham extends javax.swing.JFrame {

    /**
     * Creates new form HoaDon
     */
    Buss buss = null;
    DefaultTableModel tablemodel = null;
     String ImgPath = null;

    public SanPham() throws SQLException {
        buss = new Buss();

        initComponents();
         setLocationRelativeTo(null);
        tablemodel = (DefaultTableModel) jTable_SanPham.getModel();
        loadData();

    }

    private void loadData() throws SQLException {
        ArrayList<product> ds = new ArrayList<>();
        ds = buss.getProducts();
        tablemodel.setRowCount(0);
        int i = 1;
        System.out.println(i);
        for (product sp : ds) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(sp.getSpID());
            vctData.add(sp.getSpName());
           
            vctData.add(sp.getGia());
            vctData.add(sp.getLaixuat());
            vctData.add(Integer.parseInt(sp.getGia()) + (Integer.parseInt(sp.getGia())*Integer.parseInt(sp.getLaixuat()))/100);
            vctData.add(sp.getNccID());
////
//         
            vctData.add(sp.getSoluong());
            vctData.add(sp.getMota());

            tablemodel.addRow(vctData);

        }
    }

    private void loadData(ArrayList<product> ds) throws SQLException {
         tablemodel.setRowCount(0);
        int i = 1;
        System.out.println(i);
        for (product sp : ds) {
            Vector vctData = new Vector();
            vctData.add(i);
            i++;
            vctData.add(sp.getSpID());
            vctData.add(sp.getSpName());
           
            vctData.add(sp.getGia());
            vctData.add(sp.getLaixuat());
            vctData.add(Integer.parseInt(sp.getGia()) + (Integer.parseInt(sp.getGia())*Integer.parseInt(sp.getLaixuat()))/100);
            vctData.add(sp.getNccID());
////
//         
            vctData.add(sp.getSoluong());
            vctData.add(sp.getMota());

            tablemodel.addRow(vctData);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Ten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_GiaGoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Lai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_GiaBan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_SoLuong = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_MoTa = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Ncc = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton_OpenAnh = new javax.swing.JButton();
        jLabelimg = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_SanPham = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jButton_Xoa = new javax.swing.JButton();
        jButton_TimKiem = new javax.swing.JButton();
        jButton_ThemMoi = new javax.swing.JButton();
        jButton_CapNhat = new javax.swing.JButton();
        jButton_HienThi = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jTextField_find = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lí sản phẩm");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(217, 186, 103));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÍ SẢN PHẨM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 222, 222)), "Thông tin", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(215, 173, 103))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã sản phẩm");

        jTextField_ID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_ID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 198, 107), 1, true));
        jTextField_ID.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên sản phẩm");

        jTextField_Ten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Ten.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 198, 107), 1, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Giá tiền nhập");

        jTextField_GiaGoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_GiaGoc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 198, 107), 1, true));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Phần trăm lãi");

        jTextField_Lai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Lai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 198, 107), 1, true));
        jTextField_Lai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_LaiFocusLost(evt);
            }
        });
        jTextField_Lai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LaiActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("GIá tiền bán");

        jTextField_GiaBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_GiaBan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 198, 107), 1, true));
        jTextField_GiaBan.setEnabled(false);
        jTextField_GiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GiaBanActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("%");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Ten))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_GiaGoc))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Lai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_GiaBan)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_GiaGoc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Lai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nhà cung cấp");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Số lượng");

        jTextField_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_SoLuong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 198, 107), 1, true));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setToolTipText("");

        jTextArea_MoTa.setColumns(20);
        jTextArea_MoTa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_MoTa.setRows(5);
        jTextArea_MoTa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 198, 107), 1, true));
        jScrollPane2.setViewportView(jTextArea_MoTa);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Mô tả");

        jTextField_Ncc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Ncc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 198, 107), 1, true));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_SoLuong)
                            .addComponent(jTextField_Ncc))))
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addGap(89, 89, 89)))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ảnh");

        jButton_OpenAnh.setBackground(new java.awt.Color(255, 252, 246));
        jButton_OpenAnh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_OpenAnh.setText("Open");
        jButton_OpenAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OpenAnhActionPerformed(evt);
            }
        });

        jLabelimg.setBackground(new java.awt.Color(153, 255, 255));
        jLabelimg.setOpaque(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_OpenAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelimg, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton_OpenAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelimg, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTable_SanPham.setBackground(new java.awt.Color(255, 246, 226));
        jTable_SanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_SanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã sản phẩm", "Tên SP", "Giá gốc", "Lãi", "Giá bán", "NCC", "Số Lượng", "Mô Tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_SanPham);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jButton_Xoa.setBackground(new java.awt.Color(210, 62, 62));
        jButton_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButton_TimKiem.setBackground(new java.awt.Color(255, 252, 246));
        jButton_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_TimKiem.setText("Tìm kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });

        jButton_ThemMoi.setBackground(new java.awt.Color(133, 247, 133));
        jButton_ThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ThemMoi.setText("Thêm mới");
        jButton_ThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemMoiActionPerformed(evt);
            }
        });

        jButton_CapNhat.setBackground(new java.awt.Color(255, 217, 134));
        jButton_CapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_CapNhat.setText("Cập nhật");
        jButton_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CapNhatActionPerformed(evt);
            }
        });

        jButton_HienThi.setBackground(new java.awt.Color(255, 252, 246));
        jButton_HienThi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_HienThi.setText("Tất Cả");
        jButton_HienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HienThiActionPerformed(evt);
            }
        });

        jButton_reset.setBackground(new java.awt.Color(210, 62, 62));
        jButton_reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_reset.setForeground(new java.awt.Color(255, 255, 255));
        jButton_reset.setText("Nhập Lại");
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });

        jTextField_find.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_find.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 198, 107), 1, true));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã sản phẩm", "Tên Sản phẩm", "Giá sản phẩm" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton_ThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jTextField_find, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jButton_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButton_HienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_reset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ThemMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_CapNhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_HienThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jButton_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_find, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ImageIcon ResizeImage(String imagePath, byte[] pic) {
        ImageIcon myImage = null;
        if (imagePath != null) {
            myImage = new ImageIcon(imagePath);
        } else {
            myImage = new ImageIcon(pic);
        }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(jLabelimg.getWidth(), jLabelimg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }

    private void jButton_OpenAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OpenAnhActionPerformed

        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jLabelimg.setIcon(ResizeImage(path, null));
            ImgPath = path;

        } else {
            System.out.println("No File Selected");
        }


    }//GEN-LAST:event_jButton_OpenAnhActionPerformed

    private void jTextField_GiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GiaBanActionPerformed

    private void jButton_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CapNhatActionPerformed

        int i = jTable_SanPham.getSelectedRow();

        if (jTextArea_MoTa.getText().trim().equals("") || jTextField_GiaBan.getText().trim().equals("") || jTextField_GiaGoc.getText().trim().equals("") || jTextField_Lai.getText().trim().equals("") || jTextField_SoLuong.getText().trim().equals("") || jTextField_Ncc.getText().trim().equals("") || jTextField_Ten.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được bỏ trống");

        } else {
            if (ImgPath != null) {
                product sp = new product(jTextField_ID.getText(), jTextField_Ten.getText(), Integer.parseInt(jTextField_SoLuong.getText()), jTextField_Lai.getText(), jTextField_GiaGoc.getText(), jTextArea_MoTa.getText(), jTextField_Ncc.getText());
//              System.out.println(ImgPath);
                try {
                    loadData(buss.getProducts());
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    InputStream img = new FileInputStream(new File(ImgPath));
                    boolean x = buss.updateSP(sp, img);
                    if (x) {
                        JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
                        loadData(buss.getProducts());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                product sp = new product(jTextField_ID.getText(), jTextField_Ten.getText(), Integer.parseInt(jTextField_SoLuong.getText()), jTextField_Lai.getText(), jTextField_GiaGoc.getText(), jTextArea_MoTa.getText(), jTextField_Ncc.getText());

                try {
                    loadData(buss.getProducts());
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    InputStream img = new FileInputStream(new File("C:\\Users\\Nguyen\\Documents\\NetBeansProjects\\Quan_Li_Cua_Hang_MayTinh\\src\\IMG\\iconuser.png"));
                    boolean x = buss.updateSP(sp);
//                System.out.println(ImgPath);
                    if (x) {
                        JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
                        loadData(buss.getProducts());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CapNhatActionPerformed

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed

        jTextArea_MoTa.setText("");
        jTextField_ID.setText("");
        jTextField_Ten.setText("");
        jTextField_Ncc.setText("");
        jTextField_SoLuong.setText("");
        jTextField_Lai.setText("");
        jTextField_GiaGoc.setText("");
        jTextField_GiaBan.setText("");
        jLabelimg.setIcon(null);

        
    }//GEN-LAST:event_jButton_resetActionPerformed
   
    private void jButton_ThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemMoiActionPerformed

        int i = jTable_SanPham.getSelectedRow();

        if (jTextArea_MoTa.getText().trim().equals("") || jTextField_GiaBan.getText().trim().equals("") || jTextField_GiaGoc.getText().trim().equals("") || jTextField_Lai.getText().trim().equals("") || jTextField_SoLuong.getText().trim().equals("") || jTextField_Ncc.getText().trim().equals("") || jTextField_Ten.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Các trường không được bỏ trống");

        } else {
            if (ImgPath != null) {
                product sp = new product(jTextField_ID.getText(), jTextField_Ten.getText(), Integer.parseInt(jTextField_SoLuong.getText()), jTextField_Lai.getText(), jTextField_GiaGoc.getText(), jTextArea_MoTa.getText(), jTextField_Ncc.getText());
//              System.out.println(ImgPath);
                try {
                    loadData(buss.getProducts());
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    InputStream img = new FileInputStream(new File(ImgPath));
                    boolean x = buss.insertSP(sp, img);
                    if (x) {
                        JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                        loadData(buss.getProducts());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                product sp = new product(jTextField_ID.getText(), jTextField_Ten.getText(), Integer.parseInt(jTextField_SoLuong.getText()), jTextField_Lai.getText(), jTextField_GiaGoc.getText(), jTextArea_MoTa.getText(), jTextField_Ncc.getText());

                try {
                    loadData(buss.getProducts());
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    InputStream img = new FileInputStream(new File("C:\\Users\\Nguyen\\Documents\\NetBeansProjects\\Quan_Li_Cua_Hang_MayTinh\\src\\IMG\\iconuser.png"));
                    boolean x = buss.insertSP(sp, img);
//                System.out.println(ImgPath);
                    if (x) {
                        JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                        loadData(buss.getProducts());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


    }//GEN-LAST:event_jButton_ThemMoiActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed

        int i = jTable_SanPham.getSelectedRow();

        boolean x = false;
        try {
            x = buss.deleteSP(Integer.parseInt(jTextField_ID.getText()));
//            System.out.println(x);
            if (x) {
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
//                buss.get().remove(i);
                try {
                    loadData(buss.getProducts());
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLiKhachHang.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jTable_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SanPhamMouseClicked

        int i = jTable_SanPham.getSelectedRow();
        jTextField_ID.setText(buss.getDsProduct().get(i).getSpID());
        jTextArea_MoTa.setText(buss.getDsProduct().get(i).getMota());
        int x = Integer.parseInt(buss.getDsProduct().get(i).getGia()) + (Integer.parseInt(buss.getDsProduct().get(i).getGia()) * Integer.parseInt(buss.getDsProduct().get(i).getLaixuat()) / 100);
        jTextField_GiaBan.setText(String.valueOf(x));
        jTextField_GiaGoc.setText(buss.getDsProduct().get(i).getGia());
        jTextField_Ten.setText(buss.getDsProduct().get(i).getSpName());
        jTextField_Lai.setText(buss.getDsProduct().get(i).getLaixuat());
        jTextField_Ncc.setText(buss.getDsProduct().get(i).getNccID());
        jTextField_SoLuong.setText(String.valueOf(buss.getDsProduct().get(i).getSoluong()));

        ImageIcon img = null;
        img = ResizeImage(null, buss.getDsProduct().get(i).getImg());

        jLabelimg.setIcon(img);


    }//GEN-LAST:event_jTable_SanPhamMouseClicked

    private void jTextField_LaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LaiActionPerformed

    private void jButton_HienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HienThiActionPerformed

        try {
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(SanPham.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_HienThiActionPerformed

    private void jTextField_LaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_LaiFocusLost
        int i = jTable_SanPham.getSelectedRow();
        int x = Integer.parseInt(jTextField_GiaGoc.getText()) + (Integer.parseInt(jTextField_GiaGoc.getText()) * Integer.parseInt(jTextField_Lai.getText()) / 100);
        jTextField_GiaBan.setText(String.valueOf(x));

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LaiFocusLost

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed


        int i = jComboBox1.getSelectedIndex();
        switch(i){
            case 0:
            {
                try {
                    loadData(buss.findMasp(Integer.parseInt(jTextField_find.getText())));
                } catch (SQLException ex) {
//                    Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                break;
            case 1:
            {
                try {
                    loadData(buss.findTensp(jTextField_find.getText()));
                } catch (SQLException ex) {
//                    Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                break;
            case 2:
            {
//                try {
//                    loadData(buss.find(jTextFieldFind.getText()));
//                } catch (SQLException ex) {
//                    Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
//                }
            }
                break;
            

        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SanPham().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SanPham.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CapNhat;
    private javax.swing.JButton jButton_HienThi;
    private javax.swing.JButton jButton_OpenAnh;
    private javax.swing.JButton jButton_ThemMoi;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelimg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_SanPham;
    private javax.swing.JTextArea jTextArea_MoTa;
    private javax.swing.JTextField jTextField_GiaBan;
    private javax.swing.JTextField jTextField_GiaGoc;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Lai;
    private javax.swing.JTextField jTextField_Ncc;
    private javax.swing.JTextField jTextField_SoLuong;
    private javax.swing.JTextField jTextField_Ten;
    private javax.swing.JTextField jTextField_find;
    // End of variables declaration//GEN-END:variables
}
